name: Sec Tools
description: A collection of various security scanners
author: https://github.com/sjames-au
requirements:
  - docker
configuration:
  properties:
    image-version:
      type: string
  additionalProperties: false