steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files:
          - hooks/**
          - bin/**

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: library-example
