steps:
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/**
            - bin/**
  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.2.0:
          id: sjames-au/sectools
  - label: ":dogfood: gitleaks"
    command: gitleaks
    plugins:
      - sjames-au/sectools#gitleaks:
          
